// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/Tp4Parser202420.gold"
import gold.*;
import gold.structures.*;
import gold.structures.automaton.*;
import gold.structures.bag.*;
import gold.structures.collection.*;
import gold.structures.deque.*;
import gold.structures.disjointset.*;
import gold.structures.graph.*;
import gold.structures.heap.*;
import gold.structures.list.*;
import gold.structures.map.*;
import gold.structures.multimap.*;
import gold.structures.point.*;
import gold.structures.queue.*;
import gold.structures.set.*;
import gold.structures.stack.*;
import gold.structures.tree.*;
import gold.structures.tree.binary.*;
import gold.structures.tree.nary.*;
import gold.structures.tuple.*;
import gold.structures.turingMachine.*;
import gold.swing.*;
import gold.swing.icon.*;
import gold.swing.icon.ajaxload.*;
import gold.swing.icon.famfamfam.*;
import gold.swing.icon.gold.*;
import gold.swing.icon.jlfgr.*;
import gold.swing.icon.wikimedia.*;
import gold.swing.icon.windows.*;
import gold.swing.look.*;
import gold.swing.util.*;
import gold.test.*;
import gold.test.automaton.*;
import gold.test.general.*;
import gold.test.graph.*;
import gold.util.*;
import gold.visualization.*;
import gold.visualization.automaton.*;
import gold.visualization.graph.*;
import gold.visualization.quadtree.*;
import gold.visualization.turingMachine.*;
import gold.visualization.util.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class Tp4Parser202420 {
  public static Object toSet(Object C) {
    int $line=0;
    Object $result=null;
    $try:try {
      gold.structures.set.ISet $v1=$newSet();
      $v2:for (Object x:GCollections.unmodifiableCollection(C)) {
        $v1.add(x);
      }
      $result=$v1;
      if (true) break $try;
      $line=3;
      $rethrow(new RuntimeException("The function \"toSet(C:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Tp4Parser202420.class,"toSet",$line);
    }
    return $result;
  }
  public static IPushdownAutomaton createParser(Object A) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=6;
      Object Q=$fix($opIntvlY(0,6));
      $line=7;
      Object \u03A3=$fix($opUnionY(Tp4Parser202420.toSet(A),GCollections.asSet(' ','\n','\t')));
      $line=9;
      Object \u0393=$fix(GCollections.asSet('0','R','P','V'));
      $line=10;
      Object q_0=$fix(0);
      $line=11;
      Object F=$fix(GCollections.asSet(0));
      $line=12;
      Object M=$fix($invokeConstructor(GPushdownAutomaton.class,new Object[]{Q,\u03A3,\u0393,q_0,F}));
      $line=13;
      Object SkipChars=$fix(GCollections.asSet(' ','\n','\t'));
      $line=17;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(0,1,$cast(java.lang.String.class,'f')),new Object[]{});
      $line=20;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(0,1,$cast(java.lang.String.class,'l')),new Object[]{});
      $line=23;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(0,1,$cast(java.lang.String.class,'r')),new Object[]{});
      $line=25;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(1,0,$cast(java.lang.String.class,'#')),new Object[]{});
      $line=28;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(0,0,$cast(java.lang.String.class,'i')),new Object[]{"V"});
      $line=29;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(0,0,$cast(java.lang.String.class,':')),new Object[]{"V"});
      $line=32;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(0,0,$cast(java.lang.String.class,'i')),new Object[]{});
      $line=33;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(0,0,$cast(java.lang.String.class,'#')),new Object[]{});
      $line=36;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(0,0,$cast(java.lang.String.class,'c')),new Object[]{});
      $line=37;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(0,0,$cast(java.lang.String.class,'u')),new Object[]{});
      $line=38;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(0,0,$cast(java.lang.String.class,'d')),new Object[]{});
      $line=41;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(0,2,$cast(java.lang.String.class,'F')),new Object[]{});
      $line=42;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,1,$cast(java.lang.String.class,'#')),new Object[]{});
      $line=43;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,2,$cast(java.lang.String.class,':')),new Object[]{"V"});
      $line=44;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,1,$cast(java.lang.String.class,'i')),new Object[]{"V"});
      $line=45;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(1,1,$cast(java.lang.String.class,':')),new Object[]{"V"});
      $line=46;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(1,0,$cast(java.lang.String.class,'i')),new Object[]{"V"});
      $line=50;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(0,3,$cast(java.lang.String.class,'R')),new Object[]{});
      $line=51;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(3,4,$cast(java.lang.String.class,'#')),new Object[]{});
      $line=52;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(3,4,$cast(java.lang.String.class,':')),new Object[]{});
      $line=53;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(4,0,$cast(java.lang.String.class,'[')),new Object[]{"R"});
      $line=54;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(0,0,$cast(java.lang.String.class,']')),new Object[]{"R"});
      $line=57;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(0,5,$cast(java.lang.String.class,'T')),new Object[]{"P"});
      $line=58;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(5,0,$cast(java.lang.String.class,'i')),new Object[]{});
      $line=59;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(0,0,$cast(java.lang.String.class,'E')),new Object[]{"P"});
      $line=60;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(0,0,$cast(java.lang.String.class,'[')),new Object[]{"R"});
      $line=61;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(0,0,$cast(java.lang.String.class,']')),new Object[]{"R"});
      $line=64;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(0,1,$cast(java.lang.String.class,'m')),new Object[]{"0"});
      $line=65;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(1,6,$cast(java.lang.String.class,'"')),new Object[]{"0"});
      $line=66;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(6,1,$cast(java.lang.String.class,'i')),new Object[]{});
      $line=69;
      for (Object $v3:GCollections.unmodifiableCollection(Q)) {
        Object q=$v3;
        $line=70;
        for (Object $v4:GCollections.unmodifiableCollection(SkipChars)) {
          Object s=$v4;
          $line=71;
          $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(q,q,$cast(java.lang.String.class,$opAdditY("",s))),new Object[]{});
        }
      }
      $line=75;
      $result=M;
      if (true) break $try;
      $line=76;
      $rethrow(new RuntimeException("The function \"createParser(A:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Tp4Parser202420.class,"createParser",$line);
    }
    return $cast(IPushdownAutomaton.class,$result);
  }
}
