// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/TP2CatEven.gold"
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class TP2CatEven {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=14;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,TP2CatEven.createAutomaton()));
      $line=15;
      Utilities.test($cast(gold.structures.automaton.IAutomaton.class,TP2CatEven.createAutomaton()));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,TP2CatEven.class,"main",$line);
    }
  }
  public static IAutomaton createAutomaton() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=20;
      Object Q=$fix(GCollections.asSet("even","odd","c_state","ca_state","c_state_odd","ca_state_odd"));
      $line=23;
      Object \u03A3=$fix(GCollections.asSet('a','c','h','t'));
      $line=26;
      Object q_0=$fix("even");
      $line=29;
      Object F=$fix(GCollections.asSet("even","c_state","ca_state"));
      $line=32;
      Object \u03B4=$fix(new Object[]{new Object[]{"even",'c',"c_state"},new Object[]{"even",'a',"even"},new Object[]{"even",'h',"even"},new Object[]{"even",'t',"even"},new Object[]{"odd",'c',"c_state_odd"},new Object[]{"odd",'a',"odd"},new Object[]{"odd",'h',"odd"},new Object[]{"odd",'t',"odd"},new Object[]{"c_state_odd",'c',"c_state_odd"},new Object[]{"c_state_odd",'a',"ca_state_odd"},new Object[]{"c_state_odd",'h',"odd"},new Object[]{"c_state_odd",'t',"odd"},new Object[]{"c_state_odd",'a',"ca_state_odd"},new Object[]{"ca_state_odd",'c',"c_state_odd"},new Object[]{"ca_state_odd",'a',"odd"},new Object[]{"ca_state_odd",'h',"odd"},new Object[]{"ca_state_odd",'t',"even"},new Object[]{"c_state",'c',"c_state"},new Object[]{"c_state",'a',"ca_state"},new Object[]{"c_state",'h',"even"},new Object[]{"c_state",'t',"even"},new Object[]{"ca_state",'c',"c_state"},new Object[]{"ca_state",'a',"even"},new Object[]{"ca_state",'h',"even"},new Object[]{"ca_state",'t',"odd"},new Object[]{"even",'t',"even"},new Object[]{"odd",'t',"odd"},new Object[]{"even",'a',"even"},new Object[]{"odd",'a',"odd"},new Object[]{"c_state",'a',"ca_state"}});
      $line=70;
      $result=$invokeConstructor(GDeterministicAutomaton.class,new Object[]{Q,\u03A3,q_0,F,\u03B4});
      if (true) break $try;
      $line=71;
      $rethrow(new RuntimeException("The function \"createAutomaton()\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,TP2CatEven.class,"createAutomaton",$line);
    }
    return $cast(IAutomaton.class,$result);
  }
}
