// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/Coder.gold"
import gold.*;
import gold.structures.*;
import gold.structures.automaton.*;
import gold.structures.bag.*;
import gold.structures.collection.*;
import gold.structures.deque.*;
import gold.structures.disjointset.*;
import gold.structures.graph.*;
import gold.structures.heap.*;
import gold.structures.list.*;
import gold.structures.map.*;
import gold.structures.multimap.*;
import gold.structures.point.*;
import gold.structures.queue.*;
import gold.structures.set.*;
import gold.structures.stack.*;
import gold.structures.tree.*;
import gold.structures.tree.binary.*;
import gold.structures.tree.nary.*;
import gold.structures.tuple.*;
import gold.structures.turingMachine.*;
import gold.swing.*;
import gold.swing.icon.*;
import gold.swing.icon.ajaxload.*;
import gold.swing.icon.famfamfam.*;
import gold.swing.icon.gold.*;
import gold.swing.icon.jlfgr.*;
import gold.swing.icon.wikimedia.*;
import gold.swing.icon.windows.*;
import gold.swing.look.*;
import gold.swing.util.*;
import gold.test.*;
import gold.test.automaton.*;
import gold.test.general.*;
import gold.test.graph.*;
import gold.util.*;
import gold.visualization.*;
import gold.visualization.automaton.*;
import gold.visualization.graph.*;
import gold.visualization.quadtree.*;
import gold.visualization.turingMachine.*;
import gold.visualization.util.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class Coder {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static Object Alph=null;
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=7;
      Object coder=$fix(Coder.createTransducer(Alph));
      $line=8;
      System.out.println($message(new Object[]{"Input strings of a,b,c"}));
      $line=11;
      Utilities.test($cast(gold.structures.automaton.IAutomaton.class,coder));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Coder.class,"main",$line);
    }
  }
  public static ITransducer createTransducer(Object A) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=18;
      Object Q=$fix($opCartsY(new Object[]{$opIntvlY(0,1),$opIntvlY(0,1),$opIntvlY(0,1)}));
      $line=19;
      Object \u03A3=$fix($opIntvlY('a','c'));
      $line=20;
      Object O=$fix($opIntvlY('0','7'));
      $line=21;
      Object q_0=$fix(GCollections.asList(0,0,0));
      $line=22;
      Object F=$fix(Q);
      $line=23;
      $result=$invokeConstructor(GDeterministicTransducer.class,new Object[]{Q,\u03A3,O,q_0,F,new GMethod(Coder.class,"\u03B4"),new GMethod(Coder.class,"g"),new GMethod(Coder.class,"h")});
      if (true) break $try;
      $line=24;
      $rethrow(new RuntimeException("The function \"createTransducer(A:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Coder.class,"createTransducer",$line);
    }
    return $cast(ITransducer.class,$result);
  }
  public static Object g(java.lang.Iterable $v1) {
    int $line=0;
    Object $result=null;
    $try:try {
      java.util.Iterator $v2=GCollections.unmodifiableCollection($v1).iterator();
      Object ays=$v2.next();
      Object bes=$v2.next();
      Object ces=$v2.next();
      $result=$opAdditY($opAdditY($opMultpY(ays,4),$opMultpY(bes,2)),ces);
      if (true) break $try;
      $line=28;
      $rethrow(new RuntimeException("The function \"g(\u27E8ays,bes,ces\u27E9:java.lang.Iterable)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Coder.class,"g",$line);
    }
    return $result;
  }
  public static Object \u03B4(java.lang.Iterable $v3, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      java.util.Iterator $v4=GCollections.unmodifiableCollection($v3).iterator();
      Object ays=$v4.next();
      Object bes=$v4.next();
      Object ces=$v4.next();
      $line=32;
      if ($opEqualY(\u03C3,'a')) {
        $line=32;
        $result=GCollections.asList($opModulY($opAdditY(ays,1),2),bes,ces);
        if (true) break $try;
      }
      else {
        $line=33;
        if ($opEqualY(\u03C3,'b')) {
          $line=33;
          $result=GCollections.asList(ays,$opModulY($opAdditY(bes,1),2),ces);
          if (true) break $try;
        }
        else {
          $line=34;
          $result=GCollections.asList(ays,bes,$opModulY($opAdditY(ces,1),2));
          if (true) break $try;
        }
      }
      $line=36;
      $rethrow(new RuntimeException("The function \"\u03B4(\u27E8ays,bes,ces\u27E9:java.lang.Iterable,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Coder.class,"\u03B4",$line);
    }
    return $result;
  }
  public static Object h(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=39;
      $result="";
      if (true) break $try;
      $line=40;
      $rethrow(new RuntimeException("The function \"h(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Coder.class,"h",$line);
    }
    return $result;
  }
}
